version: '3.8'
services:
  php:
    build: ./docker/php
    volumes:
      - .:/var/www:delegated
    environment:
      APP_ENV: "dev"
  nginx:
    image: nginx:1.18
    ports:
      - "8086:80"
    volumes:
      - .:/var/www:delegated
      - ./docker/nginx:/etc/nginx/conf.d
    depends_on:
      - php
